---
- get_url:
    url: "{{ zeppelin_url }}"
    dest: /root/zeppelin-{{zeppelin_version}}-bin-all.tar.gz
- unarchive:
    copy: no
    src: /root/zeppelin-{{zeppelin_version}}-bin-all.tar.gz
    dest:  /opt
    creates: /opt/zeppelin-{{zeppelin_version}}-bin-all
- file:
    src: "/opt/zeppelin-{{zeppelin_version}}-bin-all"
    dest: "/opt/zeppelin"
    state: link
